org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
mod_version=0.1.0
maven_group=win.transgirls
archives_base_name=streamproof
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.17.2
loom_version=1.14-SNAPSHOT
fabric_api_version=0.141.1+1.21.11